# Generated by Django 2.2.16 on 2022-06-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220604_1929'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='followings are unique',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique'),
        ),
    ]
